### ISSUE TITLE
quick code review

### ISSUE THREAD

**Issue by qcaas-nhs-sjt** [lsc-sde/iac-flux-neulander#1]
https://github.com/lsc-sde/iac-flux-neulander/blob/5cff6e0371e9bac850f0576a6169cc1c827854ba/sandbox/kustomization.yaml#L4-L5

The file referenced here would be expected to be a kubernetes resource. Flux will not know how to interpret it.

This seems to me like a case for configmap generator inside of kustomize rather than a resource:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: neulander
configMapGenerator:
  - name: neulander-config
    files:
      - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true # doesn't give the resource a dynamic name but a static one
resources: [] # empty as there are no resources
```

This config map would then be fed into a helmrelease object as it's configuration

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neulander
spec:
  targetNamespace: neulander
  releaseName: neulander
  chart:
    spec:
      chart: neulander
      version: 0.1.0 # ideally this should be configurable using environment substitution
      sourceRef: # This refers to a helmrepository that you'd have to create
        kind: HelmRepository
        name: neulander
        namespace: neulander
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true

  valuesFrom:
  - kind: ConfigMap
    name: neulander-config # refers to the above configmap created by the configmap generator

  dependsOn:
  - name: keda # tells flux that that this needs keda to be installed first
    namespace: keda
```

**Comment by qcaas-nhs-sjt** [comment]
only include helm config that you want to change for your environment, leave the rest the same:

https://github.com/lsc-sde/iac-flux-neulander/blob/5cff6e0371e9bac850f0576a6169cc1c827854ba/sandbox/values.yaml#L1-L47

becomes:

```yaml
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    xlscsde.nhs.uk/dns-record: neulander${environment_dns_suffix}
  hosts:
    - host: ${environment_dns_prefix}neulander${environment_dns_suffix}.${private_dnz_zone}

  tls:
    enabled: true
    secretName: ${environment_dns_prefix}neulander${environment_dns_suffix}.${private_dnz_zone}-tls
```

**Comment by qcaas-nhs-sjt** [comment]
https://github.com/lsc-sde/iac-flux-neulander/blob/5cff6e0371e9bac850f0576a6169cc1c827854ba/sandbox/values.yaml#L45-L47

This will only work if the secret _${environment_dns_prefix}jupyter${environment_dns_suffix}.${private_dnz_zone}-tls_  is present. aside from the typo from the jupyter this secret will need creating as it will look for it in the local namespace.

In our system the secrets are created by the [secrets distributor](https://lsc-sde.github.io/lsc-sde/Developer-Guide/Getting-Started.html#secrets)

in this case you will need one as follows:

```yaml
apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: ${environment_dns_prefix}neulander${environment_dns_suffix}.${private_dnz_zone}-tls
  annotations:
    xlscsde.nhs.uk/secretUsage: "Wildcard Certificate"
spec:
  name: ${environment_dns_prefix}neulander${environment_dns_suffix}.${private_dnz_zone}-tls
  type: kubernetes.io/tls
  secrets:
  - from: WildcardCertificate
    to: tls.crt
  - from: WildcardCertificateKey
    to: tls.key
```
